### ISSUE TITLE
PHP 5.6 needed for 9.1+

### ISSUE THREAD

**Issue by axlroden** [driket/docker-glpi#2] opened 2016-07-11 09:00 UTC
Just a heads up PHP 5.6 is needed for 9.1+ i wanted to use this for testing the beta but was unable.

**Comment by driket** [comment] 2016-07-26 14:37
Hi. 

I'm currently testing 9.1 (from the 9.1-RC1 tarball), so far no warnings from PHP. 

From the 9.1 readme.md file: "PHP 5.4 or higher".  
The current version in the Docker image is "PHP 5.5.9-1ubuntu4.11 ".
So it should do the job.

Have you encountered some trouble with the version of PHP used within the Docker image ?

**Comment by driket** [comment] 2016-09-06 11:20
I'm closing the issue since I often have to deploy GLPI 9.1 and I can't reproduce the problem.

Also, I've fixed the Ubuntu version to 14 in the Dockerfile since the new version doesn't support PHP 5.X.

Thanks for your feedback and don't hesitate to open a new issue if something is wrong with this image to run GLPI 9.1+.

**Closed as completed by driket** 2016-09-06 11:20 UTC
